services:
  app:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - ./compareware.db:/app/compareware.db
    environment:
      - RUST_LOG=info
      - LEPTOS_ENV=production
    restart: unless-stopped